name: Deploy to Test Server

on:
  push:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}
      
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}

      - name: Add test server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TEST_SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Trigger remote deploy script
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.TEST_SERVER_USER }}@${{ secrets.TEST_SERVER_HOST }} \
            set -e
            cd ~/recapp
            git fetch origin
            git checkout --force "${BRANCH_NAME}"
            "bash ~/deploy_recapp_to_test.sh"
            echo "✅ Deployed branch '${BRANCH_NAME}' to test server."
            EOF
